services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "9000:9000"

  db:
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - geartoshare
    
  frontend:
    build:
      dockerfile: Dockerfile.dev
    container_name: geartoshare_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
